import { createElement } from "react";
import {
  Award,
  BadgeCheck,
  Bell,
  Boxes,
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarClock,
  CalendarSync,
  CheckCheck,
  Circle,
  ClipboardCheck,
  ClipboardList,
  FileBadge,
  GraduationCap,
  Grid3x3,
  HardHat,
  History,
  IdCard,
  Languages,
  Layers,
  LayoutDashboard,
  Library,
  ListChecks,
  ListOrdered,
  MessagesSquare,
  Network,
  OctagonAlert,
  PenLine,
  Scale,
  ScanText,
  ScrollText,
  Search,
  ShieldAlert,
  ShieldCheck,
  SquareCheck,
  TriangleAlert,
  Users,
  Wrench,
  type LucideIcon,
  type LucideProps
} from "lucide-react";

/** One icon per module name in content/landing.ts (platform.groups + platform.everywhere). */
const map: Record<string, LucideIcon> = {
  // Flagship modules
  HIRAC: ShieldAlert,
  "Training (LMS)": GraduationCap,
  Inspections: ClipboardCheck,
  "Incidents & CAPA": TriangleAlert,
  "5×5 risk matrix": Grid3x3,
  "Hierarchy of control": Layers,
  Permits: FileBadge,
  "Legislative refs": Scale,
  PPE: HardHat,
  "Versioned records": History,
  "Document library": Library,
  "Worker sign-off": PenLine,
  Acknowledgements: CheckCheck,
  "Toolbox talks": MessagesSquare,
  "Attendance records": CalendarCheck,
  "Contractor docs": Briefcase,
  Translation: Languages,
  "Ontario courses": GraduationCap,
  Certificates: Award,
  "Dynamic forms": ClipboardList,
  Findings: Search,
  "Cert expiry": CalendarClock,
  "Asset register": Boxes,
  Maintenance: Wrench,
  "Compliance dashboard": LayoutDashboard,
  "Non-conformance": OctagonAlert,
  "RCA · 5 Whys": ListOrdered,
  Fishbone: Network,
  "Corrective actions": ListChecks,
  "Effectiveness review": BadgeCheck,
  Tasks: SquareCheck,
  Notifications: Bell,
  "Multi-site": Building2,
  Departments: Users,
  "Role-based access": ShieldCheck,
  "Audit trail": ScrollText,
  "Employee profiles": IdCard,
  "Document Intelligence": ScanText,
  "Calendar sync": CalendarSync
};

/** Renders the module's icon; unknown names fall back to a plain circle. */
export function ModuleIcon({ name, ...props }: { name: string } & LucideProps) {
  return createElement(map[name] ?? Circle, props);
}
